// ============================================================================
// SharedRouter.ts — Generated execute() dispatcher for Pachca node (shared by V1 and V2)
// DO NOT EDIT — this file is auto-generated by generate-n8n.ts
// ============================================================================

import type { IExecuteFunctions, INodeExecutionData, IDataObject, IHttpRequestMethods } from 'n8n-workflow';
import {
	makeApiRequest,
	makeApiRequestAllPages,
	resolveResourceLocator,
	buildButtonRows,
	cleanFileAttachments,
	resolveFormBlocksFromParams,
	uploadFileToS3,
	uploadAvatar,
	splitAndValidateCommaList,
	simplifyItem,
	sanitizeBaseUrl,
} from './GenericFunctions';

// ============================================================================
// Types
// ============================================================================

interface PathParam {
	api: string;
	n8n: string;
	locator?: boolean;
	v1Fallback?: string;
}

interface FieldMap {
	api: string;
	n8n: string;
	isArray?: boolean;
	arrayType?: 'int' | 'string';
	locator?: boolean;
	subKey?: string;
	default?: unknown;
}

interface QueryMap {
	api: string;
	n8n: string;
	locator?: boolean;
	required?: boolean;
	isArray?: boolean;
	arrayType?: 'int' | 'string';
}

interface RouteConfig {
	method: IHttpRequestMethods;
	path: string;
	pathParams?: PathParam[];
	wrapperKey?: string;
	siblingFields?: string[];
	paginated?: boolean;
	noDataWrapper?: boolean;
	bodyMap?: FieldMap[];
	optionalBodyMap?: FieldMap[];
	queryMap?: QueryMap[];
	optionalQueryMap?: QueryMap[];
	v1Collection?: string;
	special?: string;
}

// ============================================================================
// V1 Compatibility Maps
// ============================================================================

/** v1 resource name → v2 resource name */
const V1_RESOURCE_MAP: Record<string, string> = {
	customFields: 'customProperty',
	status: 'profile',
	reactions: 'reaction',
};

/** v1 operation name → v2 operation name (per v2 resource) */
const V1_OP_MAP: Record<string, Record<string, string>> = {
	message: { send: 'create', getById: 'get' },
	user: { getById: 'get' },
	chat: { getById: 'get' },
	groupTag: { getById: 'get', getUsers: 'getAllUsers' },
	profile: { getProfile: 'get' },
	customProperty: { getCustomProperties: 'get' },
	reaction: { addReaction: 'create', deleteReaction: 'delete', getReactions: 'getAll' },
	thread: { createThread: 'create', getThread: 'get' },
	form: { createView: 'create' },
	file: { upload: 'create' },
};

// ============================================================================
// Routes Table
// ============================================================================

const ROUTES: Record<string, Record<string, RouteConfig>> = {
	security: {
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/audit_events',
			paginated: true,
			optionalQueryMap: [{ api: 'start_time', n8n: 'startTime' }, { api: 'end_time', n8n: 'endTime' }, { api: 'event_key', n8n: 'eventKey' }, { api: 'actor_id', n8n: 'actorId' }, { api: 'actor_type', n8n: 'actorType' }, { api: 'entity_id', n8n: 'entityId' }, { api: 'entity_type', n8n: 'entityType' }],
		},
	},
	bot: {
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/bots/{id}',
			pathParams: [{ api: 'id', n8n: 'botId' }],
			wrapperKey: 'bot',
			special: 'botWebhook',
		},
		getAllEvents: {
			method: 'GET' as IHttpRequestMethods,
			path: '/webhooks/events',
			paginated: true,
		},
		removeEvents: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/webhooks/events/{id}',
			pathParams: [{ api: 'id', n8n: 'id' }],
		},
	},
	chat: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/chats',
			wrapperKey: 'chat',
			bodyMap: [
				{ api: 'name', n8n: 'chatName' },
			],
			optionalBodyMap: [
				{ api: 'member_ids', n8n: 'memberIds', isArray: true, arrayType: 'int' },
				{ api: 'group_tag_ids', n8n: 'groupTagIds', isArray: true, arrayType: 'int' },
				{ api: 'channel', n8n: 'channel' },
				{ api: 'public', n8n: 'public' },
			],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/chats',
			paginated: true,
			queryMap: [{ api: 'sort', n8n: 'sort' }, { api: 'order', n8n: 'order' }, { api: 'availability', n8n: 'availability' }, { api: 'last_message_at_after', n8n: 'lastMessageAtAfter' }, { api: 'last_message_at_before', n8n: 'lastMessageAtBefore' }],
			optionalQueryMap: [{ api: 'personal', n8n: 'personal' }],
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/chats/{id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'chatId' }],
		},
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/chats/{id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'chatId' }],
			wrapperKey: 'chat',
			optionalBodyMap: [
				{ api: 'name', n8n: 'chatName' },
				{ api: 'public', n8n: 'public' },
			],
		},
		archive: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/chats/{id}/archive',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'chatId' }],
		},
		unarchive: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/chats/{id}/unarchive',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'chatId' }],
		},
		getMembers: {
			method: 'GET' as IHttpRequestMethods,
			path: '/chats/{chatId}/members',
			pathParams: [{ api: 'chatId', n8n: 'chatId' }],
			paginated: true,
			v1Collection: 'chatMembersOptions',
			optionalQueryMap: [{ api: 'role', n8n: 'role' }, { api: 'limit', n8n: 'limit' }, { api: 'cursor', n8n: 'cursor' }],
		},
		addUsers: {
			method: 'POST' as IHttpRequestMethods,
			path: '/chats/{chatId}/members',
			pathParams: [{ api: 'chatId', n8n: 'chatId' }],
			bodyMap: [{ api: 'member_ids', n8n: 'memberIds', isArray: true, arrayType: 'int' }],
			optionalBodyMap: [{ api: 'silent', n8n: 'silent' }],
		},
		removeUser: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/chats/{chatId}/members/{userId}',
			pathParams: [{ api: 'chatId', n8n: 'chatId' }, { api: 'userId', n8n: 'userId' }],
		},
		updateRole: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/chats/{chatId}/members/{userId}',
			pathParams: [{ api: 'chatId', n8n: 'chatId' }, { api: 'userId', n8n: 'userId' }],
			bodyMap: [{ api: 'role', n8n: 'newRole' }],
		},
		leaveChat: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/chats/{chatId}/leave',
			pathParams: [{ api: 'chatId', n8n: 'chatId' }],
		},
	},
	member: {
		addGroupTags: {
			method: 'POST' as IHttpRequestMethods,
			path: '/chats/{id}/group_tags',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }],
			bodyMap: [
				{ api: 'group_tag_ids', n8n: 'groupTagIds', isArray: true, arrayType: 'int' },
			],
		},
		removeGroupTags: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/chats/{id}/group_tags/{tag_id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }, { api: 'tag_id', n8n: 'tagId' }],
		},
		leave: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/chats/{id}/leave',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/chats/{id}/members',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }],
			paginated: true,
			queryMap: [{ api: 'role', n8n: 'role' }],
		},
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/chats/{id}/members',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }],
			bodyMap: [
				{ api: 'member_ids', n8n: 'memberIds', isArray: true, arrayType: 'int' },
			],
			optionalBodyMap: [
				{ api: 'silent', n8n: 'silent' },
			],
		},
		delete: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/chats/{id}/members/{user_id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }, { api: 'user_id', n8n: 'userId', locator: true }],
		},
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/chats/{id}/members/{user_id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true }, { api: 'user_id', n8n: 'userId', locator: true }],
			bodyMap: [
				{ api: 'role', n8n: 'role' },
			],
		},
	},
	groupTag: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/group_tags',
			wrapperKey: 'group_tag',
			bodyMap: [
				{ api: 'name', n8n: 'groupTagName' },
			],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/group_tags',
			paginated: true,
			queryMap: [{ api: 'names', n8n: 'names', isArray: true, arrayType: 'string' }],
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/group_tags/{id}',
			pathParams: [{ api: 'id', n8n: 'groupTagId' }],
		},
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/group_tags/{id}',
			pathParams: [{ api: 'id', n8n: 'groupTagId' }],
			wrapperKey: 'group_tag',
			bodyMap: [
				{ api: 'name', n8n: 'groupTagName' },
			],
		},
		delete: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/group_tags/{id}',
			pathParams: [{ api: 'id', n8n: 'groupTagId' }],
		},
		getAllUsers: {
			method: 'GET' as IHttpRequestMethods,
			path: '/group_tags/{id}/users',
			pathParams: [{ api: 'id', n8n: 'groupTagId' }],
			paginated: true,
		},
		addTags: {
			method: 'POST' as IHttpRequestMethods,
			path: '/chats/{groupTagChatId}/group_tags',
			pathParams: [{ api: 'groupTagChatId', n8n: 'groupTagChatId' }],
			bodyMap: [{ api: 'group_tag_ids', n8n: 'groupTagIds', isArray: true, arrayType: 'int' }],
		},
		removeTag: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/chats/{groupTagChatId}/group_tags/{tagId}',
			pathParams: [{ api: 'groupTagChatId', n8n: 'groupTagChatId' }, { api: 'tagId', n8n: 'tagId' }],
		},
	},
	message: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/messages',
			wrapperKey: 'message',
			siblingFields: ['link_preview'],
			special: 'messageButtons',
			bodyMap: [
				{ api: 'entity_type', n8n: 'entityType' },
				{ api: 'entity_id', n8n: 'entityId', locator: true },
				{ api: 'content', n8n: 'content' },
			],
			optionalBodyMap: [
				{ api: 'files', n8n: 'files', subKey: 'file' },
				{ api: 'parent_message_id', n8n: 'parentMessageId' },
				{ api: 'display_avatar_url', n8n: 'displayAvatarUrl' },
				{ api: 'display_name', n8n: 'displayName' },
				{ api: 'skip_invite_mentions', n8n: 'skipInviteMentions' },
				{ api: 'link_preview', n8n: 'linkPreview' },
			],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/messages',
			paginated: true,
			queryMap: [{ api: 'chat_id', n8n: 'chatId', locator: true, required: true }, { api: 'sort', n8n: 'sort' }, { api: 'order', n8n: 'order' }],
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/messages/{id}',
			pathParams: [{ api: 'id', n8n: 'id', v1Fallback: 'messageId' }],
		},
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/messages/{id}',
			pathParams: [{ api: 'id', n8n: 'id', v1Fallback: 'messageId' }],
			wrapperKey: 'message',
			special: 'messageButtons',
			optionalBodyMap: [
				{ api: 'content', n8n: 'content' },
				{ api: 'files', n8n: 'files', subKey: 'file' },
				{ api: 'display_avatar_url', n8n: 'displayAvatarUrl' },
				{ api: 'display_name', n8n: 'displayName' },
			],
		},
		delete: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/messages/{id}',
			pathParams: [{ api: 'id', n8n: 'id', v1Fallback: 'messageId' }],
		},
		pin: {
			method: 'POST' as IHttpRequestMethods,
			path: '/messages/{id}/pin',
			pathParams: [{ api: 'id', n8n: 'id', v1Fallback: 'messageId' }],
		},
		unpin: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/messages/{id}/pin',
			pathParams: [{ api: 'id', n8n: 'id', v1Fallback: 'messageId' }],
		},
		getReadMembers: {
			method: 'GET' as IHttpRequestMethods,
			path: '/messages/{messageId}/read_member_ids',
			pathParams: [{ api: 'messageId', n8n: 'messageId' }],
			paginated: true,
			v1Collection: 'readMembersOptions',
			optionalQueryMap: [{ api: 'per', n8n: 'readMembersPer' }, { api: 'page', n8n: 'readMembersPage' }],
		},
		unfurl: {
			method: 'POST' as IHttpRequestMethods,
			path: '/messages/{messageId}/link_previews',
			pathParams: [{ api: 'messageId', n8n: 'messageId' }],
			special: 'unfurlLinkPreviews',
			bodyMap: [{ api: 'link_previews', n8n: 'linkPreviews' }],
		},
	},
	linkPreview: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/messages/{id}/link_previews',
			pathParams: [{ api: 'id', n8n: 'id' }],
			bodyMap: [
				{ api: 'link_previews', n8n: 'linkPreviews' },
			],
		},
	},
	reaction: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/messages/{id}/reactions',
			pathParams: [{ api: 'id', n8n: 'reactionsMessageId' }],
			bodyMap: [
				{ api: 'code', n8n: 'reactionsReactionCode' },
			],
			optionalBodyMap: [
				{ api: 'name', n8n: 'name' },
			],
		},
		delete: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/messages/{id}/reactions',
			pathParams: [{ api: 'id', n8n: 'reactionsMessageId' }],
			queryMap: [{ api: 'code', n8n: 'reactionsReactionCode', required: true }, { api: 'name', n8n: 'name' }],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/messages/{id}/reactions',
			pathParams: [{ api: 'id', n8n: 'reactionsMessageId' }],
			paginated: true,
			v1Collection: 'reactionsOptions',
			optionalQueryMap: [{ api: 'limit', n8n: 'reactionsPer' }, { api: 'cursor', n8n: 'reactionsCursor' }],
		},
	},
	readMember: {
		getAllReadMemberIds: {
			method: 'GET' as IHttpRequestMethods,
			path: '/messages/{id}/read_member_ids',
			pathParams: [{ api: 'id', n8n: 'id' }],
			paginated: true,
		},
	},
	thread: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/messages/{id}/thread',
			pathParams: [{ api: 'id', n8n: 'threadMessageId' }],
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/threads/{id}',
			pathParams: [{ api: 'id', n8n: 'threadThreadId' }],
		},
	},
	profile: {
		getInfo: {
			method: 'GET' as IHttpRequestMethods,
			path: '/oauth/token/info',
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/profile',
		},
		updateAvatar: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/profile/avatar',
			special: 'avatarUpload',
		},
		deleteAvatar: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/profile/avatar',
		},
		getStatus: {
			method: 'GET' as IHttpRequestMethods,
			path: '/profile/status',
		},
		updateStatus: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/profile/status',
			wrapperKey: 'status',
			bodyMap: [
				{ api: 'emoji', n8n: 'statusEmoji' },
				{ api: 'title', n8n: 'statusTitle' },
			],
			optionalBodyMap: [
				{ api: 'expires_at', n8n: 'statusExpiresAt' },
				{ api: 'is_away', n8n: 'isAway' },
				{ api: 'away_message', n8n: 'awayMessage' },
			],
		},
		deleteStatus: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/profile/status',
		},
	},
	search: {
		getAllChats: {
			method: 'GET' as IHttpRequestMethods,
			path: '/search/chats',
			paginated: true,
			queryMap: [{ api: 'query', n8n: 'query' }],
			optionalQueryMap: [{ api: 'order', n8n: 'order' }, { api: 'created_from', n8n: 'createdFrom' }, { api: 'created_to', n8n: 'createdTo' }, { api: 'active', n8n: 'active' }, { api: 'chat_subtype', n8n: 'chatSubtype' }, { api: 'personal', n8n: 'personal' }],
		},
		getAllMessages: {
			method: 'GET' as IHttpRequestMethods,
			path: '/search/messages',
			paginated: true,
			queryMap: [{ api: 'query', n8n: 'query' }],
			optionalQueryMap: [{ api: 'order', n8n: 'order' }, { api: 'created_from', n8n: 'createdFrom' }, { api: 'created_to', n8n: 'createdTo' }, { api: 'chat_ids', n8n: 'chatIds', isArray: true, arrayType: 'int' }, { api: 'user_ids', n8n: 'userIds', isArray: true, arrayType: 'int' }, { api: 'active', n8n: 'active' }],
		},
		getAllUsers: {
			method: 'GET' as IHttpRequestMethods,
			path: '/search/users',
			paginated: true,
			queryMap: [{ api: 'query', n8n: 'query' }],
			optionalQueryMap: [{ api: 'sort', n8n: 'sort' }, { api: 'order', n8n: 'order' }, { api: 'created_from', n8n: 'createdFrom' }, { api: 'created_to', n8n: 'createdTo' }, { api: 'company_roles', n8n: 'companyRoles', isArray: true, arrayType: 'string' }],
		},
	},
	task: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/tasks',
			wrapperKey: 'task',
			bodyMap: [
				{ api: 'kind', n8n: 'taskKind' },
			],
			optionalBodyMap: [
				{ api: 'content', n8n: 'taskContent' },
				{ api: 'due_at', n8n: 'taskDueAt' },
				{ api: 'priority', n8n: 'taskPriority' },
				{ api: 'performer_ids', n8n: 'performerIds', isArray: true, arrayType: 'int' },
				{ api: 'chat_id', n8n: 'chatId' },
				{ api: 'all_day', n8n: 'allDay' },
				{ api: 'custom_properties', n8n: 'customProperties', subKey: 'property' },
			],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/tasks',
			paginated: true,
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/tasks/{id}',
			pathParams: [{ api: 'id', n8n: 'id' }],
		},
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/tasks/{id}',
			pathParams: [{ api: 'id', n8n: 'id' }],
			wrapperKey: 'task',
			optionalBodyMap: [
				{ api: 'kind', n8n: 'kind' },
				{ api: 'content', n8n: 'content' },
				{ api: 'due_at', n8n: 'dueAt' },
				{ api: 'priority', n8n: 'priority' },
				{ api: 'performer_ids', n8n: 'performerIds', isArray: true, arrayType: 'int' },
				{ api: 'status', n8n: 'status' },
				{ api: 'all_day', n8n: 'allDay' },
				{ api: 'done_at', n8n: 'doneAt' },
				{ api: 'custom_properties', n8n: 'customProperties', subKey: 'property' },
			],
		},
		delete: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/tasks/{id}',
			pathParams: [{ api: 'id', n8n: 'id' }],
		},
	},
	user: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/users',
			wrapperKey: 'user',
			siblingFields: ['skip_email_notify'],
			bodyMap: [
				{ api: 'email', n8n: 'email' },
			],
			optionalBodyMap: [
				{ api: 'first_name', n8n: 'firstName' },
				{ api: 'last_name', n8n: 'lastName' },
				{ api: 'phone_number', n8n: 'phoneNumber' },
				{ api: 'nickname', n8n: 'nickname' },
				{ api: 'department', n8n: 'department' },
				{ api: 'title', n8n: 'title' },
				{ api: 'role', n8n: 'role' },
				{ api: 'suspended', n8n: 'suspended' },
				{ api: 'list_tags', n8n: 'listTags', isArray: true, arrayType: 'string' },
				{ api: 'custom_properties', n8n: 'customProperties', subKey: 'property' },
				{ api: 'skip_email_notify', n8n: 'skipEmailNotify' },
			],
		},
		getAll: {
			method: 'GET' as IHttpRequestMethods,
			path: '/users',
			paginated: true,
			special: 'userGetAllFilters',
			v1Collection: 'additionalOptions',
			optionalQueryMap: [{ api: 'query', n8n: 'query' }],
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/users/{id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'userId' }],
		},
		update: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/users/{id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'userId' }],
			wrapperKey: 'user',
			optionalBodyMap: [
				{ api: 'first_name', n8n: 'firstName' },
				{ api: 'last_name', n8n: 'lastName' },
				{ api: 'email', n8n: 'email' },
				{ api: 'phone_number', n8n: 'phoneNumber' },
				{ api: 'nickname', n8n: 'nickname' },
				{ api: 'department', n8n: 'department' },
				{ api: 'title', n8n: 'title' },
				{ api: 'role', n8n: 'role' },
				{ api: 'suspended', n8n: 'suspended' },
				{ api: 'list_tags', n8n: 'listTags', isArray: true, arrayType: 'string' },
				{ api: 'custom_properties', n8n: 'customProperties', subKey: 'property' },
			],
		},
		delete: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/users/{id}',
			pathParams: [{ api: 'id', n8n: 'id', locator: true, v1Fallback: 'userId' }],
		},
		updateAvatar: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/users/{user_id}/avatar',
			pathParams: [{ api: 'user_id', n8n: 'userId' }],
			special: 'avatarUpload',
		},
		deleteAvatar: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/users/{user_id}/avatar',
			pathParams: [{ api: 'user_id', n8n: 'userId' }],
		},
		getStatus: {
			method: 'GET' as IHttpRequestMethods,
			path: '/users/{user_id}/status',
			pathParams: [{ api: 'user_id', n8n: 'userId' }],
		},
		updateStatus: {
			method: 'PUT' as IHttpRequestMethods,
			path: '/users/{user_id}/status',
			pathParams: [{ api: 'user_id', n8n: 'userId' }],
			wrapperKey: 'status',
			bodyMap: [
				{ api: 'emoji', n8n: 'emoji' },
				{ api: 'title', n8n: 'title' },
			],
			optionalBodyMap: [
				{ api: 'expires_at', n8n: 'expiresAt' },
				{ api: 'is_away', n8n: 'isAway' },
				{ api: 'away_message', n8n: 'awayMessage' },
			],
		},
		deleteStatus: {
			method: 'DELETE' as IHttpRequestMethods,
			path: '/users/{user_id}/status',
			pathParams: [{ api: 'user_id', n8n: 'userId' }],
		},
	},
	form: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/views/open',
			wrapperKey: 'view',
			siblingFields: ['type', 'trigger_id', 'private_metadata', 'callback_id'],
			special: 'formBlocks',
			bodyMap: [
				{ api: 'title', n8n: 'formTitle', default: '' },
				{ api: 'type', n8n: 'type', default: 'modal' },
				{ api: 'trigger_id', n8n: 'triggerId' },
			],
			optionalBodyMap: [
				{ api: 'close_text', n8n: 'closeText' },
				{ api: 'submit_text', n8n: 'submitText' },
				{ api: 'private_metadata', n8n: 'privateMetadata' },
				{ api: 'callback_id', n8n: 'callbackId' },
			],
		},
		processSubmission: {
			method: 'GET' as IHttpRequestMethods,
			path: '/profile',
			special: 'formProcessSubmission',
		},
	},
	export: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/chats/exports',
			noDataWrapper: true,
			bodyMap: [
				{ api: 'start_at', n8n: 'startAt' },
				{ api: 'end_at', n8n: 'endAt' },
				{ api: 'webhook_url', n8n: 'webhookUrl' },
			],
			optionalBodyMap: [
				{ api: 'chat_ids', n8n: 'chatIds', isArray: true, arrayType: 'int' },
				{ api: 'skip_chats_file', n8n: 'skipChatsFile' },
			],
		},
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/chats/exports/{id}',
			pathParams: [{ api: 'id', n8n: 'id' }],
			noDataWrapper: true,
			special: 'exportDownload',
		},
	},
	customProperty: {
		get: {
			method: 'GET' as IHttpRequestMethods,
			path: '/custom_properties',
			queryMap: [{ api: 'entity_type', n8n: 'entityType', required: true }],
		},
	},
	file: {
		create: {
			method: 'POST' as IHttpRequestMethods,
			path: '/uploads',
			special: 'fileUpload',
		},
	},
};

// ============================================================================
// Router Entry Point
// ============================================================================

export async function router(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
	const items = this.getInputData();
	const returnData: INodeExecutionData[] = [];
	const nodeVersion = this.getNode().typeVersion;

	for (let i = 0; i < items.length; i++) {
		try {
			let resource = this.getNodeParameter('resource', i) as string;
			let operation = this.getNodeParameter('operation', i) as string;

			// v1 compat: map old resource/operation names to v2
			if (nodeVersion === 1) {
				resource = V1_RESOURCE_MAP[resource] ?? resource;
				operation = V1_OP_MAP[resource]?.[operation] ?? operation;
			}

			const route = ROUTES[resource]?.[operation];
			if (!route) {
				throw new Error(`Unknown operation: ${resource}.${operation}`);
			}

			const result = await executeRoute.call(this, route, resource, i, nodeVersion);
			returnData.push(...result.map(item => ({ ...item, pairedItem: { item: i } })));
		} catch (error) {
			if (this.continueOnFail()) {
				returnData.push({ json: { error: (error as Error).message }, pairedItem: { item: i } });
			} else {
				throw error;
			}
		}
	}

	return [returnData];
}

// ============================================================================
// Generic Route Executor
// ============================================================================

async function executeRoute(
	this: IExecuteFunctions,
	route: RouteConfig,
	resource: string,
	i: number,
	nodeVersion: number,
): Promise<INodeExecutionData[]> {
	// === Special-only operations (no API call needed) ===
	if (route.special === 'fileUpload') {
		const result = await uploadFileToS3(this, i);
		return [{ json: result }];
	}
	if (route.special === 'formProcessSubmission') {
		// v1 only: pass through form submission data from webhook input
		const inputData = this.getInputData()[i].json;
		return [{ json: inputData }];
	}
	if (route.special === 'exportDownload') {
		const exportId = this.getNodeParameter('id', i) as number;
		const credentials = await this.getCredentials('pachcaApi');
		const base = sanitizeBaseUrl(credentials.baseUrl as string);
		const resp = await this.helpers.httpRequestWithAuthentication.call(this, 'pachcaApi', {
			method: 'GET',
			url: `${base}/chats/exports/${exportId}`,
			ignoreHttpStatusErrors: true,
			returnFullResponse: true,
			disableFollowRedirect: true,
		}) as { statusCode: number; headers: Record<string, string>; body: unknown };
		const location = resp.headers?.location;
		if (location) {
			return [{ json: { id: exportId, url: location } as unknown as IDataObject }];
		}
		if (typeof resp.body === 'object' && resp.body) {
			return [{ json: resp.body as IDataObject }];
		}
		return [{ json: { id: exportId, success: true } as unknown as IDataObject }];
	}
	if (route.special === 'avatarUpload') {
		let avatarUrl = route.path;
		for (const pp of route.pathParams ?? []) {
			const value = this.getNodeParameter(pp.n8n, i) as number;
			avatarUrl = avatarUrl.replace(`{${pp.api}}`, String(value));
		}
		const result = await uploadAvatar(this, i, avatarUrl);
		return [{ json: result }];
	}
	// === Build URL with path params ===
	let url = route.path;
	for (const pp of route.pathParams ?? []) {
		let value: number | string;
		if (pp.locator) {
			value = resolveResourceLocator(this, pp.n8n, i, pp.v1Fallback);
		} else {
			try {
				value = this.getNodeParameter(pp.n8n, i) as number;
			} catch (e) {
				if (pp.v1Fallback) {
					value = this.getNodeParameter(pp.v1Fallback, i) as number;
				} else {
					throw e;
				}
			}
		}
		if (value === undefined || value === null || value === '') {
			throw new Error(`Missing required path parameter: ${pp.n8n}`);
		}
		url = url.replace(`{${pp.api}}`, String(value));
	}

	// === Build body from required fields ===
	const body: IDataObject = {};
	for (const fm of route.bodyMap ?? []) {
		let raw: unknown;
		if (fm.locator) {
			raw = resolveResourceLocator(this, fm.n8n, i);
		} else if (fm.default !== undefined) {
			try { raw = this.getNodeParameter(fm.n8n, i); } catch { raw = fm.default; }
		} else {
			raw = this.getNodeParameter(fm.n8n, i);
		}
		if (fm.isArray && typeof raw === 'string') {
			body[fm.api] = splitAndValidateCommaList(this, raw, fm.n8n, fm.arrayType!, i);
		} else {
			body[fm.api] = raw as IDataObject;
		}
	}

	// === Read optional body fields from collection ===
	const collectionName = (nodeVersion === 1 && route.v1Collection) ? route.v1Collection : 'additionalFields';
	let additional: IDataObject = {};
	try { additional = this.getNodeParameter(collectionName, i, {}) as IDataObject; } catch { /* no collection */ }

	for (const fm of route.optionalBodyMap ?? []) {
		let val: unknown = additional[fm.n8n];

		// If not in collection, try as top-level param (v1 compat for V1_TOP_LEVEL_PARAMS)
		if (val === undefined) {
			try { val = this.getNodeParameter(fm.n8n, i, undefined); } catch { /* not present */ }
		}

		if (val === undefined || val === null || val === '') continue;

		// fixedCollection: extract inner array using subKey
		if (fm.subKey && typeof val === 'object' && !Array.isArray(val)) {
			val = (val as IDataObject)[fm.subKey] ?? val;
		}
		if (fm.isArray && typeof val === 'string') {
			body[fm.api] = splitAndValidateCommaList(this, val, fm.n8n, fm.arrayType!, i);
		} else if (fm.locator && typeof val === 'object' && val !== null && (val as IDataObject).__rl) {
			body[fm.api] = (val as IDataObject).value;
		} else {
			body[fm.api] = val as IDataObject;
		}
	}

	// === Read top-level query params ===
	const qs: IDataObject = {};
	for (const qm of route.queryMap ?? []) {
		try {
			let val: unknown;
			if (qm.locator) {
				val = resolveResourceLocator(this, qm.n8n, i);
			} else {
				val = this.getNodeParameter(qm.n8n, i);
			}
			if (val !== undefined && val !== null && val !== '') {
				if (qm.isArray && typeof val === 'string') {
					qs[qm.api] = splitAndValidateCommaList(this, val, qm.n8n, qm.arrayType!, i);
				} else {
					qs[qm.api] = val as IDataObject;
				}
			}
		} catch (e) {
			if (qm.required) throw e;
		}
	}

	// Read query params from collection, with top-level fallback (same pattern as optionalBodyMap)
	for (const qm of route.optionalQueryMap ?? []) {
		let val: unknown = additional[qm.n8n];
		if (val === undefined) {
			try { val = this.getNodeParameter(qm.n8n, i, undefined); } catch { /* not present */ }
		}
		if (val !== undefined && val !== null && val !== '') {
			if (qm.isArray && typeof val === 'string') {
				qs[qm.api] = splitAndValidateCommaList(this, val, qm.n8n, qm.arrayType!, i);
			} else {
				qs[qm.api] = val;
			}
		}
	}

	// === Special handlers ===
	if (route.special === 'messageButtons') {
		const buttons = buildButtonRows(this, i);
		if (buttons !== null) body.buttons = buttons;
		const files = cleanFileAttachments(this, i);
		if (files.length) body.files = files;
	}
	if (route.special === 'formBlocks') {
		const blocks = resolveFormBlocksFromParams(this, i);
		if (blocks.length) body.blocks = blocks;
		// v1 compat: in JSON mode, title/close_text/submit_text may be inside the JSON
		// Override empty body fields with values from parsed JSON
		let rawJson = '';
		try { rawJson = this.getNodeParameter('formBlocks', i, '') as string; } catch { /* */ }
		if (!rawJson) { try { rawJson = this.getNodeParameter('customFormJson', i, '') as string; } catch { /* */ } }
		if (rawJson) {
			try {
				const parsed = JSON.parse(rawJson);
				if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
					if (!body.title && parsed.title) body.title = parsed.title;
					if (!body.close_text && parsed.close_text) body.close_text = parsed.close_text;
					if (!body.submit_text && parsed.submit_text) body.submit_text = parsed.submit_text;
				}
			} catch { /* not valid JSON or not an object */ }
		}
	}
	if (route.special === 'unfurlLinkPreviews') {
		// v1 compat: linkPreviews was a fixedCollection { preview: [{ url, title, description, imageUrl }] }
		// v2: linkPreviews is a JSON string. API expects { "url": { title, description, image_url } }
		const raw = body.link_previews;
		if (raw && typeof raw === 'object' && !Array.isArray(raw) && (raw as IDataObject).preview) {
			const previews = (raw as IDataObject).preview as IDataObject[];
			const converted: IDataObject = {};
			for (const p of previews) {
				if (!p.url) continue;
				const entry: IDataObject = {};
				if (p.title) entry.title = p.title;
				if (p.description) entry.description = p.description;
				if (p.imageUrl) entry.image_url = p.imageUrl;
				converted[p.url as string] = entry;
			}
			body.link_previews = converted;
		} else if (typeof raw === 'string') {
			try { body.link_previews = JSON.parse(raw); } catch { /* leave as-is */ }
		}
	}
	if (route.special === 'botWebhook') {
		let webhookUrl: string | undefined;
		try { webhookUrl = this.getNodeParameter('webhookUrl', i, '') as string; } catch { /* */ }
		if (webhookUrl) {
			body.webhook = { outgoing_url: webhookUrl };
		}
	}

	// === Wrap body in key ===
	let finalBody: IDataObject | undefined;
	if (Object.keys(body).length > 0) {
		if (route.wrapperKey) {
			const inner: IDataObject = {};
			const outer: IDataObject = {};
			const siblingSet = new Set(route.siblingFields ?? []);
			for (const [k, v] of Object.entries(body)) {
				if (siblingSet.has(k)) {
					outer[k] = v;
				} else {
					inner[k] = v;
				}
			}
			finalBody = { [route.wrapperKey]: inner, ...outer };
		} else {
			finalBody = body;
		}
	}

	// === Execute API call ===
	if (route.paginated) {
		let results = await makeApiRequestAllPages.call(
			this, route.method, url, qs, i, resource, nodeVersion,
		);

		// v1 client-side post-filters for user.getAll
		if (route.special === 'userGetAllFilters' && nodeVersion === 1) {
			let filterOptions: IDataObject = {};
			try { filterOptions = this.getNodeParameter('filterOptions', i, {}) as IDataObject; } catch { /* */ }

			const filterRole = filterOptions.filterRole as string[] | undefined;
			const filterBot = filterOptions.filterBot as string | undefined;
			const filterSuspended = filterOptions.filterSuspended as string | undefined;
			const filterInviteStatus = filterOptions.filterInviteStatus as string[] | undefined;

			if (filterRole?.length || (filterBot && filterBot !== 'all') ||
				(filterSuspended && filterSuspended !== 'all') || filterInviteStatus?.length) {
				results = results.filter(item => {
					const d = item.json;
					if (filterRole?.length && !filterRole.includes(d.role as string)) return false;
					if (filterBot === 'users' && d.bot === true) return false;
					if (filterBot === 'bots' && d.bot !== true) return false;
					if (filterSuspended === 'active' && d.suspended === true) return false;
					if (filterSuspended === 'suspended' && d.suspended !== true) return false;
					if (filterInviteStatus?.length && !filterInviteStatus.includes(d.invite_status as string)) return false;
					return true;
				});
			}
		}

		return results;
	}

	const response = await makeApiRequest.call(
		this, route.method, url, finalBody,
		Object.keys(qs).length > 0 ? qs : undefined, i,
	);

	// === Handle response ===
	if (route.method === 'DELETE') {
		return [{ json: { success: true } }];
	}

	// Handle 204 No Content for non-DELETE methods (archive, unarchive, pin, addMembers, etc.)
	if (!response || (typeof response === 'object' && Object.keys(response).length === 0)) {
		return [{ json: { success: true } }];
	}

	if (route.noDataWrapper) {
		if (!response || (typeof response === 'object' && Object.keys(response).length === 0)) {
			return [{ json: { success: true } as unknown as IDataObject }];
		}
		return [{ json: response }];
	}

	const data = (response.data as IDataObject) ?? response;

	// Simplify for GET single item (v2 only)
	if (nodeVersion >= 2 && route.method === 'GET' && !route.paginated) {
		let doSimplify = false;
		try { doSimplify = this.getNodeParameter('simplify', i, false) as boolean; } catch { /* */ }
		if (doSimplify) {
			return [{ json: simplifyItem(data, resource) }];
		}
	}

	return [{ json: data }];
}
